title:              Clean Blog
email:              fsangaref@gmail.com
description:        A Blog for Deep Learning and Robotics
author:             Fousseyni 
baseurl:            ""
url:                "https://fousseyni-sang.github.io"

# Social Profiles
twitter_username:   que neni
github_username:    Fousseyni-Sang
facebook_username:  sang-fousseyni
instagram_username:  
linkedin_username:  www.linkedin.com/in/fousseyni-sangare

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
